### ISSUE TITLE
Chmod fails when running as non-root user

### ISSUE THREAD

**Issue by cz4rny** [paketo-buildpacks/npm-install#371]
This buildpack runs `chmod` on the project's directory.

## Expected Behavior
Buildpacks is able to continue on userspace (non-root) execution.

## Current Behavior
Fails on `chmod`, e.g.:

```bash
Paketo NPM Install Buildpack 0.10.0
  Resolving installation process
    Process inputs:
      node_modules      -> "Not found"
      npm-cache         -> "Not found"
      package-lock.json -> "Found"
    Selected NPM build process: 'npm ci'
  Executing build environment install process
    Running 'npm ci --unsafe-perm --cache /layers/paketo-buildpacks_npm-install/npm-cache'
      Completed in 35.006s
  Configuring build environment
    NODE_ENV -> "development"
    PATH     -> "$PATH:/layers/paketo-buildpacks_npm-install/build-modules/node_modules/.bin"
  Generating SBOM for /layers/paketo-buildpacks_npm-install/build-modules
chmod /builds/p2s/gp2s-search/gp2s-search-frontend: operation not permitted
```

## Possible Solution
Continue if `chmod` failed.

## Steps to Reproduce
Run the buildpack with non-root privileges, i.e. a `.gitlab-ci.yaml`

```yaml
stages:
  - build

default:
  tags:
    - linux
    - amd64
    - docker
 
build-image:
  stage: build
  image: paketobuildpacks/builder:full
  # Access to GitLab Container Registry for Paketo lifecycle
  before_script:
    - mkdir ~/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_JOB_TOKEN\"}}}" >> ~/.docker/config.json
  variables:
    PLATFORM_DIR: /tmp/platform
  script:
    # creator binary doesn't read environment variables, but reads platform files.
    # Defining variables as per the the Platform Interface
    # https://github.com/buildpacks/spec/blob/main/platform.md#user-provided-variables
    - cp -r /platform "$PLATFORM_DIR"
    - echo build > "$PLATFORM_DIR/env/BP_NODE_RUN_SCRIPTS"
    - /cnb/lifecycle/creator
      -platform "$PLATFORM_DIR"
      -app=.
      $CI_REGISTRY_IMAGE:latest
```

## Motivations
I'd like to be able to use newer paketo buildpacks in userspace builds.
